title: Molecular Biology Projects by Tam To
description: Hello! My name is Tam. Welcome to this small portfolio that demonstrates some of my molecular biology analyses. This encompasses analysis of single cell sequencing and proteomics data.
theme: jekyll-theme-minimal
